version: "3"

services:
    cdn:
        build: .
        environment:
            - CDN_STORAGE_PATH=/srv/cdn
            - REDIS_HOST=redis://redis
        volumes:
            - ./:/usr/src/rs-cdn
            - ./log:/usr/src/rs-cdn/log
        command: ./target/x86_64-unknown-linux-gnu/debug/rs_cdn
        networks:
            - cdn
        depends_on:
            redis:
                condition: service_started
    redis:
        image: redis
        networks:
            - cdn
        ports:
            - "6379:6379"
        environment:
            # This disables persistence
            - REDIS_SAVE=""
            - REDIS_APPENDONLY=no
    nginx:
        image: nginx
        ports:
            - 80:80
        networks:
            - cdn
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            cdn:
                condition: service_started

networks:
    cdn:
